name-template: "$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
  - title: "📦 Dependencies"
    labels:
      - "docker dependency"
      - "github dependency"
      - "go dependency"
  - title: "✏️ Documentation"
    labels:
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
exclude-labels:
  - "skip-changelog"
template: |
  ## Changes

  $CHANGES
