version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Staffbase/yamllint-action

linters:
  default: none
  enable:
    - bodyclose
    - gosec
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unused
    - whitespace
