before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "registry.staffbase.com/public/yamllint-action:{{ .Tag }}"
      - "registry.staffbase.com/public/yamllint-action:{{ .Major }}"
      - "registry.staffbase.com/public/yamllint-action:{{ .Major }}.{{ .Minor }}"
      - "registry.staffbase.com/public/yamllint-action:latest"
    extra_files:
    - entrypoint.sh

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
