name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Test
        run: go test ./...

  release-dry-run:
    if: github.ref != 'refs/heads/master' || !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout yamllint action
      uses: actions/checkout@v3

    - name: Release Dry Run
      uses: goreleaser/goreleaser-action@v3.2.0
      with:
        version: latest
        args: release --rm-dist --snapshot --skip-announce --skip-publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
