---
name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Test
        run: go test ./...

  release-dry-run:
    if: github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout yamllint action
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Release Dry Run
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: latest
          args: release --clean --snapshot --skip=announce --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependabot-automerge:
    name: Auto Merge (Dependabot)
    needs:
      - test
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@v7.2.0
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
