name: Release

on:
  push:
    tags:
      - 'v[1-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Login to docker registry
      uses: docker/login-action@v2.1.0
      with:
        registry: registry.staffbase.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Release
      uses: goreleaser/goreleaser-action@v3.2.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set major and minor tags
      uses: vweevers/additional-tags-action@v1
